version: "3.4"

# x-common-variables: &common-variables
#  POSTGRES_USER: postgres
#  POSTGRES_PASSWORD: password

#volumes:
#  pg_sandbox_data:
#  pg_development_data:

services:
  gateway:
    build:
      context: .
      target: gateway
    ports:
      - 22:22
      - 8022:8022
    secrets:
      - id_rsa

secrets:
  id_rsa:
    file: private_unencrypted.pem
  
#  db:
#    image: postgres:11.2
#    volumes:
#      - ./database/init:/docker-entrypoint-initdb.d
#      - "pg_${PLAID_ENV}_data:/var/lib/postgresql/data"
#    ports:
#      - 5432:5432
#    environment: *common-variables

#  server:
#    build: ./server
#    image: plaidinc/pattern-server:1.0.5
#    ports:
#      - 5000:5000
#      - 9229:9229
#    environment:
#      <<: *common-variables
#      PLAID_ENV: sandbox
#      PLAID_CLIENT_ID: 5ee564778bf3880015592d40
#      PLAID_PUBLIC_KEY: 78b859d63dbfac219ac388e5fdb0f7
#      PLAID_SECRET_DEVELOPMENT: f889eac85cbe5063b45452809f3d8f
#      PLAID_SECRET_SANDBOX: 9a6ee7b86a18ecda6e600a7faf3324
#      PORT: 5000
#      DB_PORT: 5432
#      DB_HOST_NAME: db
#    depends_on:
#      - db

#  ngrok:
#    build: ./ngrok
#    image: plaidinc/pattern-ngrok:1.0.5
#    command: ["ngrok", "http", "server:5000"]
#    ports:
#      - 4040:4040
#    depends_on:
#      - server

#  client:
#    build: ./client
#    image: plaidinc/pattern-client:1.0.5
#    ports:
#      - 3000:3000
#    environment:
#      REACT_APP_PLAID_ENV: ${PLAID_ENV}
#      REACT_APP_PLAID_PUBLIC_KEY: ${PLAID_PUBLIC_KEY}
#      REACT_APP_SERVER_PORT: ${SERVER_PORT}
#      REACT_APP_SERVER_HOST: ${SERVER_HOST}
#    depends_on:
#      - server

