version: "3.4"

services:
  gateway:
    build:
      context: .
      target: gateway
    ports:
      - 22:22
      - 8022:8022
    secrets:
      - id_rsa

secrets:
  id_rsa:
    file: private_unencrypted.pem
  
