version: "3.4"

services:
  gateway:
    build:
      context: .
      target: gateway
      dockerfile: gateway/Dockerfile
    ports:
      - 8022:8022
      - 8023:8023
    secrets:
      - id_rsa
  dummy:
    image: eexit/mirror-http-server

secrets:
  id_rsa:
    file: ./.env/private_unencrypted.pem
  
