version: "3.4"

services:
  gateway:
    build:
      context: .
      target: gateway
    ports:
      - 8022:8022
    secrets:
      - id_rsa
  dummy:
    image: eexit/mirror-http-server

secrets:
  id_rsa:
    file: private_unencrypted.pem
  
