FROM golang:latest AS build-stage

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Copy the source from the current directory to the Working Directory inside the container
COPY ./ ./

# Download packages
RUN go mod download

# Build the Go app
RUN GOOS=darwin GOARCH=arm64 go build -o ./build/gateway-macos-arm64 ./gateway
RUN GOOS=linux go build -o ./build/gateway-linux ./gateway

FROM build-stage as gateway 

# Update and install packages
RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get install sshpass

# Create SSH user and set password (replace 'your_password' with a secure password)
RUN useradd -m testuser && \
    echo "testuser:tiger" | chpasswd

RUN useradd -m probe && \
    echo "probe:probe" | chpasswd

# Configure SSH
RUN mkdir /var/run/sshd && \
    echo 'Port 8023' >> /etc/ssh/sshd_config && \
    echo 'PermitRootLogin no' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config && \
    echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'AllowTcpForwarding yes' >> /etc/ssh/sshd_config && \
    echo 'PermitTunnel yes' >> /etc/ssh/sshd_config && \
    echo 'PermitTTY no' >> /etc/ssh/sshd_config && \
    echo 'Match User probe' >> /etc/ssh/sshd_config && \
    echo '    PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'Match User testuser' >> /etc/ssh/sshd_config && \
    #  && \
    #  echo 'LogLevel DEBUG3' >> /etc/ssh/sshd_config
    echo '    ForceCommand /bin/gateway' >> /etc/ssh/sshd_config

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source from the current directory to the Working Directory inside the container
COPY ./ ./
COPY --from=build-stage /app/build/gateway-macos-arm64 /bin/gateway
# Add public key to authorized_keys file to enable pubkey auth
RUN mkdir /home/testuser/.ssh && \
    ssh-keygen -y -f /app/.env/private_unencrypted.pem > /home/testuser/.ssh/authorized_keys

# Expose port 8080 to the outside world
EXPOSE 22

# Expose SSH port
EXPOSE 8022
EXPOSE 8023

# Command to run the executable
# RUN ["/bin/gateway"]

# Start SSH server
CMD ["/usr/sbin/sshd", "-De"]