apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: neti-testing
  region: us-west-2

nodeGroups:
  - name: testing-nodegroup
    instanceType: t4g.small
    desiredCapacity: 1
    ssh:
      allow: true
