apiVersion: apps/v1
kind: Deployment
metadata:
  name: lancelot-api
  namespace: neti-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lancelot-api
  template:
    metadata:
      labels:
        app: lancelot-api
        instance-type: t2.micro
    spec:
      containers:
        - name: lancelot-api
          image: registry.gitlab.com/mihaichiorean-tripaservices/devprod-testing-mesh/lancelot-api
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lancelot-api
  namespace: neti-testing
spec:
  selector:
    app: lancelot-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lancelot-api
  namespace: neti-testing
spec:
  selector:
    app: lancelot-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
-
